### ISSUE TITLE
Config variables - where to find?

### ISSUE THREAD

**Issue by radunCZ** [hansliss/regofetcher#1]
I'd like to regularly fetch the data from the newly installed heat pump from IVT. Could you please help?

Vendorkey is same for all IVTs, I guess, but where to find devicepassword and userpassword?
```
[myrego]
vendorkey: hnhF6XxOKdzlIrmn06PgexUr/63dvtf1/9hC6Yla0eQ=
devicepassword: <password on network module>
userpassword: <user password>
host: <IP address or hostname>
rundir: /home/pi/regofetcher
mailrcpt: Hans@Liss.pp.se
errcodes: /home/pi/regofetcher/IVT_errorcodes.json
htmltemplate: /home/pi/regofetcher/template.quik
```
The rest of config variables seems to be quite self explaining.

**Comment by hansliss** [comment]
If I remember correctly, you can find the passwords stamped on the network interface inside the heat pump. They are the same credentials you need in order to use their official mobile app. I'm not sure how to get them apart from by looking at the network adapter.
