### ISSUE TITLE
Copy of IVT_errorcodes.json

### ISSUE THREAD

**Issue by pszafer** [hansliss/regofetcher#2]
Hi,
I copied `IVT_errorcodes.json` from your repo to my Bosch Home Assistant custom component.
There is no license file so I'd like to ask if that's ok with you?

https://github.com/bosch-thermostat/bosch-thermostat-client-python

**Comment by hansliss** [comment]
Sure, no problem! Maybe give credit somewhere, but that's no biggie.

**Comment by pszafer** [comment]
Thanks! Of course you will be mentioned and your repo as well :)
